# Generated by Django 2.2.12 on 2020-05-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0009_auto_20200501_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='payment_threshold_period',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
